services:
  db:
    image: postgres:15-alpine
    container_name: circb_db
    restart: always
    environment:
      POSTGRES_DB: circb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: corporate2019
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - circb_net

  redis:
    image: redis:7-alpine
    container_name: circb_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - circb_net

  web:
    build: .
    container_name: circb_web
    restart: always
    command: gunicorn circb_projet.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - circb_net

  celery:
    build: .
    container_name: circb_celery
    restart: always
    command: celery -A circb_projet worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - circb_net

  metabase:
    image: metabase/metabase:latest
    container_name: circb_metabase
    restart: always
    expose:
      - "3000"
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: circb
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: corporate2019
      MB_DB_HOST: db
      MB_SITE_URL: "https://medisys-eid/metabase"
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    depends_on:
      - db
    networks:
      - circb_net

  nginx:
    image: nginx:alpine
    container_name: circb_nginx
    restart: always
    ports:
      - "8080:80"     # CORRIGÉ : Évite la collision avec Gunicorn
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./nginx/ssl:/etc/nginx/ssl:ro,z
      - static_volume:/app/staticfiles:ro,z
      - media_volume:/app/media:ro,z
    depends_on:
      - web
      - metabase
    networks:
      - circb_net

networks:
  circb_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: