"""
Django settings for circb_projet project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
load_dotenv(BASE_DIR / '.env')
# settings.py
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'circb_app',
    'pwa',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'circb_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'circb_projet.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),          # Nom de la base de données créée sur Postgres
        'USER': os.getenv('DB_USER'),          # Ton utilisateur PostgreSQL (par défaut 'postgres')
        'PASSWORD': os.getenv('DB_PASSWORD'), # Le mot de passe de ton utilisateur
        'HOST': os.getenv('DB_HOST'),         # Ou 'localhost'
        'PORT': os.getenv('DB_PORT'),              # Port par défaut de PostgreSQL
        'CONN_MAX_AGE': 600,
    }
}
AUTO_LOGOUT = {
    'IDLE_TIME': 600,  # 10 minutes in seconds
    'SESSION_TIME': 3600,  # Total max session time
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 1. The URL used to access static files in the browser
STATIC_URL = 'static/'

# 2. Additional directories where Django looks for static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]

# 3. The absolute path to the directory where collected static files will be placed for production
STATIC_ROOT = BASE_DIR / 'staticfiles'



PWA_APP_NAME = 'LIMS Laboratory'
PWA_APP_SHORT_NAME = 'LIMS'
PWA_APP_DESCRIPTION = "Système de suivi et de gestion des fiches d'échantillons"
PWA_APP_THEME_COLOR = '#0f172a'  # Couleur de la barre de titre (Slate 900)
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'   # Cache la barre d'adresse du navigateur !
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'

# Icônes de l'application (à placer dans vos fichiers statiques)
PWA_APP_ICONS = [
    {
        "src": "/static/images/icons-512.png",
        "sizes": "1024x1024",
        "purpose": "any"
    },
    {
        "src": "/static/images/icons-512.png",
        "sizes": "1024x1024",
        "purpose": "any"
    },
    {
        "src": "/static/images/icons-512.png",
        "sizes": "1024x1024",
        "purpose": "any"
    }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'fr-FR'