"""
Django settings for circb_projet project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirige ici si déjà connecté

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# settings.py
LOGIN_URL = '/login/'

LOGOUT_REDIRECT_URL = '/login/'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Garde la session ouverte après fermeture du navigateur
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')
load_dotenv(BASE_DIR / '.env')
# settings.py
ALLOWED_HOSTS = ['medisys-eid', 'localhost', '127.0.0.1','10.93.171.139','192.168.2.42']
METABASE_SITE_URL = "https://medisys-eid/metabase"
METABASE_SECRET_KEY =  os.getenv('METABASE_SECRET_KEY')


# Application definition
# Dit à Django de considérer la requête comme HTTPS si ce header est présent
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Assurez-vous que les cookies de session ou CSRF exigent le HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'circb_app',
    'pwa',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'circb_app.urls'
# settings.py
WHITENOISE_MANIFEST_STRICT = False
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'circb_projet.wsgi.application'
# settings.py
CELERY_BROKER_URL = 'redis://circb_redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://circb_redis:6379/0'
#CELERY_BROKER_URL = 'redis://localhost:6379/0'
#CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# settings.py

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),          # Nom de la base de données créée sur Postgres
        'USER': os.getenv('DB_USER'),          # Ton utilisateur PostgreSQL (par défaut 'postgres')
        'PASSWORD': os.getenv('DB_PASSWORD'), # Le mot de passe de ton utilisateur
        'HOST': os.getenv('DB_HOST'),         # Ou 'localhost'
        'PORT': os.getenv('DB_PORT'),              # Port par défaut de PostgreSQL
        'CONN_MAX_AGE': 600,
    }
}
AUTO_LOGOUT = {
    'IDLE_TIME': 600,  # 10 minutes in seconds
    'SESSION_TIME': 3600,  # Total max session time
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 1. The URL used to access static files in the browser
STATIC_URL = 'static/'

# 2. Additional directories where Django looks for static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]

# 3. The absolute path to the directory where collected static files will be placed for production
STATIC_ROOT = BASE_DIR / 'staticfiles'



# ==============================================================================
# PWA CONFIGURATION - MEDISYS LAB (LIMS / ERP SUITE)
# ==============================================================================

# Nom institutionnel complet
PWA_APP_NAME = 'MEDISYS EID '

# Nom court sous l'icône de l'écran d'accueil
PWA_APP_SHORT_NAME = 'MEDISYS EID'

# Description fonctionnelle du système
PWA_APP_DESCRIPTION = (
    "Plateforme ERP/LIMS de suivi centralisé, traçabilité des échantillons "
    "et gestion des registres de santé."
)

# Thème Dark Mode ERP (Slate 900 / Deep Navy)
PWA_APP_THEME_COLOR = '#0f172a'

# Couleur d'arrière-plan du Splash Screen (Évite le flash blanc au lancement)
PWA_APP_BACKGROUND_COLOR = '#0f172a'

# Mode d'affichage applicatif autonome (Sans barre de navigation)
PWA_APP_DISPLAY = 'standalone'

# Portée et point d'entrée système
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'

# Intégration de la barre d'état système sur mobile (iOS / Android)
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'

# Direction de lecture et langue officielle
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'fr-FR'

# ==============================================================================
# SPÉCIFICATIONS DES ICÔNES PWA (NORMES W3C / GOOGLE LIGHTHOUSE)
# ==============================================================================
PWA_APP_ICONS = [
    {
        "src": "/static/images/icons/icon-192x192.png",
        "sizes": "1024x1024",
        "type": "image/png",
        "purpose": "any maskable"
    },
    {
        "src": "/static/images/icons/icon-512x512.png",
        "sizes": "1024x1024",
        "type": "image/png",
        "purpose": "any maskable"
    },
    {
        "src": "/static/images/icons/icon-1024x1024.png",
        "sizes": "1024x1024",
        "type": "image/png",
        "purpose": "any"
    }
]