# 1. Redirection automatique HTTP vers HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name medisys-eid 10.93.171.139 localhost 127.0.0.1 _;

    return 301 https://$host$request_uri;
}

# 2. Serveur Sécurisé (HTTPS)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name medisys-eid 10.93.171.139 localhost 127.0.0.1;

    ssl_certificate /etc/nginx/ssl/medisys-eid+3.pem;
    ssl_certificate_key /etc/nginx/ssl/medisys-eid+3-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 50M;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Proxy vers Metabase
    location /metabase/ {
        # CORRIGÉ : Nom du service Docker dans le réseau virtuel
        proxy_pass http://metabase:3000/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_connect_timeout 90s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Proxy vers Django
    location / {
        # CORRIGÉ : Nom du service Docker dans le réseau virtuel
        proxy_pass http://circb_web:8000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_connect_timeout 300s;
        proxy_send_timeout    300s;
        proxy_read_timeout    300s;
    }
}
