# Generated by Django 6.0.3 on 2026-07-07 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=128, null=True)),
                ('prenom', models.CharField(blank=True, max_length=128, null=True)),
                ('mail', models.CharField(blank=True, max_length=128, null=True)),
                ('tel', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('sexe', models.CharField(blank=True, max_length=255, null=True)),
                ('bd_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
