# Generated by Django 6.0.3 on 2026-07-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeAccouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeAllaitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PorteEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilaxieArv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolePTME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaisonPrelevement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatPcr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Ex: biologiste, receptioniste, data-manager')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure_Hierachy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('rang', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheEchantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('date_reception', models.DateField(null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('nombre_echantillon', models.IntegerField(null=True)),
                ('date_expedition', models.DateField(null=True)),
                ('receptioniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moyen_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.moyentransport')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('code', models.SlugField(blank=True, null=True, unique=True)),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='circb_app.mere')),
                ('porte_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.porteentree')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=128, null=True)),
                ('prenom', models.CharField(blank=True, max_length=128, null=True)),
                ('mail', models.EmailField(blank=True, max_length=128, null=True)),
                ('tel', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='personnel_photos/')),
                ('sexe', models.CharField(blank=True, max_length=255, null=True)),
                ('bd_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='utilisateurs', to='circb_app.role')),
            ],
        ),
        migrations.AddField(
            model_name='mere',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.personnel'),
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang_naissance', models.IntegerField(null=True)),
                ('date_rdv', models.DateField(blank=True, null=True)),
                ('date_diagnostic_lav', models.DateField(blank=True, null=True)),
                ('date_initiation_ptme', models.DateField(blank=True, null=True)),
                ('date_diagnostic_vih', models.DateField(blank=True, null=True)),
                ('numero_grossesse', models.IntegerField(blank=True, null=True)),
                ('nb_enfant_expose', models.IntegerField(blank=True, null=True)),
                ('nb_enfant_infecte', models.IntegerField(blank=True, null=True)),
                ('present_symptome', models.BooleanField(default=False)),
                ('present_allaitement', models.BooleanField(default=False)),
                ('present_sevrage', models.BooleanField(default=False)),
                ('date_sevrage', models.DateField(blank=True, null=True)),
                ('present_cotrimoxazole', models.BooleanField(default=False)),
                ('date_cotrimoxazole', models.DateField(blank=True, null=True)),
                ('present_tarv', models.BooleanField(default=False)),
                ('date_tarv', models.DateField(blank=True, null=True)),
                ('pcr_1', models.BooleanField(default=False)),
                ('pcr_2', models.BooleanField(default=False)),
                ('autre_pcr', models.BooleanField(default=False)),
                ('date_prelevement', models.DateField()),
                ('duplicate_prelevement', models.BooleanField(default=False)),
                ('nom_preleveur', models.CharField(max_length=255)),
                ('prenom_preleveur', models.CharField(max_length=255)),
                ('contact_preleveur', models.IntegerField()),
                ('observation', models.TextField()),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echantillons', to='circb_app.ficheechantillon')),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_mere', to='circb_app.mere')),
                ('mode_accouchement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.modeaccouchement')),
                ('mode_allaitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.modeallaitement')),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_enfant', to='circb_app.patient')),
                ('porte_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.porteentree')),
                ('profilaxie_arv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.profilaxiearv')),
                ('protocole_ptme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.protocoleptme')),
                ('raison_prelevement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.raisonprelevement')),
                ('resultat_pcr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.resultatpcr')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='circb_app.structure')),
                ('hierachy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='circb_app.structure_hierachy')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='fosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_fosa', to='circb_app.structure'),
        ),
        migrations.AddField(
            model_name='ficheechantillon',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_districtuales', to='circb_app.structure'),
        ),
        migrations.AddField(
            model_name='ficheechantillon',
            name='fosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_fosa', to='circb_app.structure'),
        ),
        migrations.AddField(
            model_name='ficheechantillon',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_regionales', to='circb_app.structure'),
        ),
        migrations.AddField(
            model_name='ficheechantillon',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.transporteur'),
        ),
    ]
