# Generated by Django 6.0.3 on 2026-07-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure_Hierachy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('rang', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('tel', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='circb_app.structure')),
                ('hierachy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierachies', to='circb_app.structure_hierachy')),
            ],
        ),
        migrations.CreateModel(
            name='FicheEchantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('date_reception', models.DateField(null=True)),
                ('observation', models.TextField(null=True)),
                ('nombre_echantillon', models.IntegerField(null=True)),
                ('date_expedition', models.DateField(null=True)),
                ('receptioniste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circb_app.personnel')),
                ('moyen_transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.moyentransport')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_districtuales', to='circb_app.structure')),
                ('fosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_fosa', to='circb_app.structure')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_regionales', to='circb_app.structure')),
                ('transporteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.transporteur')),
            ],
        ),
    ]
