# Generated by Django 6.0.3 on 2026-07-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
