# Generated by Django 6.0.3 on 2026-07-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0002_moyentransport_structure_hierachy_test_transporteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheechantillon',
            name='moyen_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.moyentransport'),
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.transporteur'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='mail',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='personnel_photos/'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='hierachy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='circb_app.structure_hierachy'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='circb_app.structure'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
