# Generated by Django 6.0.3 on 2026-07-10 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0002_echantillon_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Type de PCR',
                'verbose_name_plural': 'Types de PCR',
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Configuration de Test', 'verbose_name_plural': 'Configurations de Tests'},
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='pcr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='circb_app.pcr'),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prelevement', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('echantillon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='circb_app.echantillon')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_valides', to=settings.AUTH_USER_MODEL)),
                ('resultat_pcr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultats_associes', to='circb_app.resultatpcr')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='circb_app.test')),
            ],
            options={
                'verbose_name': "Résultat d'Analyse",
                'verbose_name_plural': "Résultats d'Analyses",
                'ordering': ['-date_prelevement'],
            },
        ),
    ]
