# Generated by Django 6.0.3 on 2026-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0003_pcr_alter_test_options_alter_test_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheechantillon',
            name='numero_ordre',
            field=models.IntegerField(null=True),
        ),
    ]
