# Generated by Django 6.0.3 on 2026-07-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0004_alter_ficheechantillon_receptioniste'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeAccouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeAllaitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PorteEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilaxieArv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolePTME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaisonPrelevement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatPcr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('date_prochain_rdv', models.DateField(blank=True, null=True)),
                ('date_diagnostic_lav', models.DateField(blank=True, null=True)),
                ('date_initiation_ptme', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.personnel')),
                ('mode_accouchement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.modeaccouchement')),
                ('protocole_ptme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.protocoleptme')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('code', models.SlugField(blank=True, null=True, unique=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.personnel')),
                ('fosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_fosa', to='circb_app.structure')),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='circb_app.mere')),
                ('porte_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.porteentree')),
                ('profilaxie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.profilaxiearv')),
            ],
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('date_reception', models.DateField(null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('is_symptome_present', models.BooleanField(default=False)),
                ('is_allaitement_present', models.BooleanField(default=False)),
                ('if_yes_preciser', models.TextField(blank=True, null=True)),
                ('date_sevrage', models.DateField(blank=True, null=True)),
                ('if_not_sevrage_preciser', models.TextField(blank=True, null=True)),
                ('is_use_cotrimoxazole', models.BooleanField(default=False)),
                ('if_use_cotrimoxazole_preciser_date', models.DateField(blank=True, null=True)),
                ('is_use_tarv', models.BooleanField(default=False)),
                ('if_use_tarv_preciser_date', models.DateField(blank=True, null=True)),
                ('date_pcr1', models.DateField(blank=True, null=True)),
                ('date_pcr2', models.DateField(blank=True, null=True)),
                ('date_prelevement', models.DateField(blank=True, null=True)),
                ('again_prelevement', models.BooleanField(default=False)),
                ('nom_preleveur', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_preleveur', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_preleveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_preleveur', to='circb_app.personnel')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echantillons', to='circb_app.ficheechantillon')),
                ('fosa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_fosa', to='circb_app.structure')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.test')),
                ('mode_allaitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.modeallaitement')),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_enfant', to='circb_app.patient')),
                ('raison_prelevement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circb_app.raisonprelevement')),
                ('resultat_pcr1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_pcr1', to='circb_app.resultatpcr')),
                ('resultat_pcr2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_pcr2', to='circb_app.resultatpcr')),
                ('resultat_pcr3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_final', to='circb_app.resultatpcr')),
            ],
        ),
    ]
