# Generated by Django 6.0.3 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0006_alter_ficheechantillon_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheechantillon',
            name='date_enregistrement',
            field=models.DateField(null=True),
        ),
    ]
