# Generated by Django 6.0.3 on 2026-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0007_ficheechantillon_date_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='service',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
