# Generated by Django 6.0.3 on 2026-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0008_personnel_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheechantillon',
            name='date_Envoie_labo',
            field=models.DateField(null=True),
        ),
    ]
