# Generated by Django 6.0.3 on 2026-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0009_ficheechantillon_date_envoie_labo'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
