# Generated by Django 6.0.3 on 2026-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0010_echantillon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mere',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
