# Generated by Django 6.0.3 on 2026-07-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0011_alter_mere_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='autre_pcr',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='pcr_1',
        ),
        migrations.RemoveField(
            model_name='echantillon',
            name='pcr_2',
        ),
        migrations.AddField(
            model_name='echantillon',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons', to='circb_app.test'),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='resultat_pcr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons', to='circb_app.resultatpcr'),
        ),
    ]
