# Generated by Django 6.0.3 on 2026-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0013_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_enregistrement',
            field=models.DateField(null=True),
        ),
    ]
