# Generated by Django 6.0.3 on 2026-07-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0014_echantillon_date_enregistrement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultat',
            options={'ordering': ['-date_resultat'], 'verbose_name': "Résultat d'Analyse", 'verbose_name_plural': "Résultats d'Analyses"},
        ),
        migrations.RenameField(
            model_name='resultat',
            old_name='date_prelevement',
            new_name='date_resultat',
        ),
    ]
