# Generated by Django 6.0.3 on 2026-07-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0015_alter_resultat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheechantillon',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
