# Generated by Django 6.0.3 on 2026-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0016_ficheechantillon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
