# Generated by Django 6.0.3 on 2026-07-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0017_echantillon_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheechantillon',
            name='expediteur',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
