# Generated by Django 6.0.3 on 2026-07-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0018_ficheechantillon_expediteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='poids',
        ),
    ]
