# Generated by Django 6.0.3 on 2026-07-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0020_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatpcr',
            name='observation',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
