# Generated by Django 6.0.3 on 2026-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0021_resultatpcr_observation_delete_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeallaitement',
            name='is_artificiel',
            field=models.BooleanField(default=False),
        ),
    ]
