# Generated by Django 6.0.3 on 2026-08-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0023_roleuser_delete_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(help_text="Le nom de la route URL Django (ex: 'modifier_patient')", max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('roles_autorises', models.ManyToManyField(blank=True, help_text="Rôles ayant le droit d'accéder à cette page", related_name='routes_accessibles', to='circb_app.role')),
            ],
        ),
    ]
