# Generated by Django 6.0.3 on 2026-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0024_routeaccesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_initiation_profilaxie_arv',
            field=models.DateField(blank=True, null=True),
        ),
    ]
