# Generated by Django 6.0.3 on 2026-08-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0025_echantillon_date_initiation_profilaxie_arv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echantillon',
            options={'permissions': [('peut_voir_fiches_expedition', "Peut voir les fiches d'expédition"), ('peut_valider_resultats', "Peut valider les résultats d'analyses"), ('peut_saisir_echantillon', 'Peut enregistrer un nouvel échantillon')]},
        ),
    ]
