# Generated by Django 6.0.3 on 2026-08-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0026_alter_echantillon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('Consulter_dossier_patient', 'Consulter le dossier patient'), ('modifier_informations_patients', 'Modifier les informations des patients')]},
        ),
    ]
