# Generated by Django 6.0.3 on 2026-08-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0027_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultat',
            options={'ordering': ['-date_resultat'], 'permissions': [('Consulter_resultat_patient', 'Consulter le resultat patient'), ('modifier_resultats_patients', 'Modifier les resultats des patients'), ('supprimer_resultats_patients', 'Supprimer les resultats des patients')], 'verbose_name': "Résultat d'Analyse", 'verbose_name_plural': "Résultats d'Analyses"},
        ),
        migrations.DeleteModel(
            name='RouteAccessControl',
        ),
    ]
