# Generated by Django 6.0.3 on 2026-08-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0028_alter_resultat_options_delete_routeaccesscontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficheechantillon',
            options={'permissions': [('peut_voir_fiches_expedition', "Peut voir les fiches d'expédition"), ('peut_valider_resultats', "Peut valider les résultats d'analyses"), ('peut_saisir_echantillon', 'Peut enregistrer un nouvel échantillon')]},
        ),
    ]
