# Generated by Django 6.0.3 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0029_alter_ficheechantillon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['nom'], 'permissions': [('peut_voir_structures', 'Peut voir les structures'), ('peut_modifier_structures', 'Peut modifier les structures'), ('peut_supprimer_structures', 'Peut supprimer les structures')], 'verbose_name_plural': 'Structures'},
        ),
    ]
