# Generated by Django 6.0.3 on 2026-08-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0030_alter_structure_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echantillon',
            options={'permissions': [('peut_voir_consulter_echantillons', 'Peut consulter liste des echantillons'), ('peut_modifier_echantillons', 'Peut Modifier les echantillons'), ('peut_saisir_echantillon', 'Peut enregistrer un nouvel échantillon'), ('peut_supprimer_echantillons', 'Peut supprimer les echantillons')]},
        ),
        migrations.AlterModelOptions(
            name='ficheechantillon',
            options={'permissions': [('peut_voir_fiches_expedition', "Peut voir les fiches d'expédition"), ('peut_supprimer_fiches_expedition', "Peut supprimer les fiches d'expédition"), ('peut_saisir_fiche_expedition', "Peut enregistrer une nouvelle fiche d'expédition"), ('peut_modifier_fiches_expedition', "Peut modifier les fiches d'expédition")]},
        ),
    ]
