# Generated by Django 6.0.3 on 2026-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0031_alter_echantillon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_export_pdf', 'Peut exporter les rapports PDF'), ('access_eid_dashboard', 'Peut accéder au tableau de bord EID'), ('manage_user_roles', 'Peut gérer les rôles des utilisateurs'), ('manage_system_settings', 'Peut gérer les paramètres du système'), ('manage_rh', 'Peut gérer les ressources humaines'), ('view_audit_logs', "Peut voir les journaux d'audit")],
            },
        ),
    ]
