# Generated by Django 6.0.3 on 2026-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0032_parametresglobal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['nom'], 'permissions': [('peut_voir_structures', 'Peut voir les structures'), ('peut_modifier_structures', 'Peut modifier les structures'), ('peut_supprimer_structures', 'Peut supprimer les structures'), ('peut_ajouter_structures', 'Peut ajouter de nouvelles structures')], 'verbose_name_plural': 'Structures'},
        ),
    ]
