# Generated by Django 6.0.3 on 2026-08-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0033_alter_structure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
