# Generated by Django 6.0.3 on 2026-08-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0034_alter_structure_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_fiche', to='circb_app.ficheechantillon'),
        ),
    ]
