# Generated by Django 6.0.3 on 2026-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0035_patient_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheechantillon',
            name='code',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
