# Generated by Django 6.0.3 on 2026-08-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0036_alter_ficheechantillon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheechantillon',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
