# Generated by Django 6.0.3 on 2026-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0037_alter_ficheechantillon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mere',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
