# Generated by Django 6.0.3 on 2026-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0038_alter_mere_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
