# Generated by Django 6.0.3 on 2026-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0039_remove_patient_status_alter_patient_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
