# Generated by Django 6.0.3 on 2026-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0040_alter_patient_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolArvMere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
    ]
