# Generated by Django 6.0.3 on 2026-08-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0041_protocolarvmere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='pcr',
        ),
        migrations.DeleteModel(
            name='Pcr',
        ),
    ]
