# Generated by Django 6.0.3 on 2026-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0042_remove_test_pcr_delete_pcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='duplicate_prelevement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='mode_accouchement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='mode_allaitement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='present_allaitement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='present_symptome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='protocole_ptme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
