# Generated by Django 6.0.3 on 2026-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0043_alter_echantillon_duplicate_prelevement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtocolArvMere',
        ),
        migrations.AddField(
            model_name='echantillon',
            name='code_circb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='protocol_arv_mere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
