# Generated by Django 6.0.3 on 2026-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0044_delete_protocolarvmere_echantillon_code_circb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_initiation_tarv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_resultat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='protocole_ptme_mere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='present_sevrage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
