# Generated by Django 6.0.3 on 2026-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0045_echantillon_date_initiation_tarv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_debut_arv',
            field=models.DateField(blank=True, null=True),
        ),
    ]
