# Generated by Django 6.0.3 on 2026-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0046_echantillon_date_debut_arv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='date_prelevement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
