# Generated by Django 6.0.3 on 2026-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0047_alter_echantillon_date_prelevement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
