# Generated by Django 6.0.3 on 2026-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0048_alter_echantillon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
