# Generated by Django 6.0.3 on 2026-08-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0049_alter_echantillon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='ordre',
        ),
        migrations.AddField(
            model_name='echantillon',
            name='code_ech',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
