# Generated by Django 6.0.3 on 2026-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0050_remove_echantillon_ordre_echantillon_code_ech'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
