# Generated by Django 6.0.3 on 2026-08-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0051_echantillon_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
