# Generated by Django 6.0.3 on 2026-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0052_alter_echantillon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rang_naissance',
            field=models.IntegerField(null=True),
        ),
    ]
