# Generated by Django 6.0.3 on 2026-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0053_patient_rang_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheechantillon',
            name='transporteur',
            field=models.TextField(null=True),
        ),
    ]
