# Generated by Django 6.0.3 on 2026-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0054_alter_ficheechantillon_transporteur'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nom'], name='circb_app_p_nom_ef0322_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['prenom'], name='circb_app_p_prenom_217116_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['code'], name='circb_app_p_code_7f9ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nom', 'prenom'], name='circb_app_p_nom_c6ff13_idx'),
        ),
    ]
