# Generated by Django 6.0.3 on 2026-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0055_patient_circb_app_p_nom_ef0322_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='profilaxie_arv',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
