# Generated by Django 6.0.3 on 2026-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0056_alter_echantillon_profilaxie_arv'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='protocole_ptme_autre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
