# Generated by Django 6.0.3 on 2026-08-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0057_echantillon_protocole_ptme_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='autre_profilaxie_arv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
