# Generated by Django 6.0.3 on 2026-09-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0058_echantillon_autre_profilaxie_arv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheechantillon',
            name='receptioniste',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
