# Generated by Django 6.0.3 on 2026-09-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0059_alter_ficheechantillon_receptioniste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echantillon',
            options={'permissions': [('peut_voir_consulter_echantillons', 'Peut consulter liste des echantillons'), ('peut_modifier_echantillons', 'Peut Modifier les echantillons'), ('peut_saisir_echantillon', 'Peut enregistrer un nouvel échantillon'), ('peut_supprimer_echantillons', 'Peut supprimer les echantillons'), ('peut_voir_tableau_de_bord_echantillons', 'Peut voir le tableau de bord des echantillons')]},
        ),
    ]
