# Generated by Django 6.0.3 on 2026-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0060_alter_echantillon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_saisie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
