# Generated by Django 6.0.3 on 2026-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0061_echantillon_date_saisie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='test',
        ),
        migrations.AddField(
            model_name='echantillon',
            name='examen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='tests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
