# Generated by Django 6.0.3 on 2026-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0062_remove_echantillon_test_echantillon_examen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='contact_preleveur',
            field=models.IntegerField(null=True),
        ),
    ]
