# Generated by Django 6.0.3 on 2026-09-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0063_alter_echantillon_contact_preleveur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.ficheechantillon')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.patient')),
            ],
        ),
    ]
