# Generated by Django 6.0.3 on 2026-09-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0064_patientfiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='duplicate_prelevement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
