# Generated by Django 6.0.3 on 2026-09-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0065_alter_echantillon_duplicate_prelevement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheechantillon',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ficheechantillon',
            name='region',
        ),
    ]
