# Generated by Django 6.0.3 on 2026-09-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0066_remove_ficheechantillon_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheechantillon',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_districtuales', to='circb_app.structure'),
        ),
        migrations.AddField(
            model_name='ficheechantillon',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_regionales', to='circb_app.structure'),
        ),
    ]
