# Generated by Django 6.0.3 on 2026-09-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0067_ficheechantillon_district_ficheechantillon_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheechantillon',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_districtuales', to='circb_app.structure'),
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='fosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_fosa', to='circb_app.structure'),
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_regionales', to='circb_app.structure'),
        ),
    ]
