# Generated by Django 6.0.3 on 2026-09-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0068_alter_ficheechantillon_district_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientFiche',
        ),
    ]
