# Generated by Django 6.0.3 on 2026-09-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0069_delete_patientfiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fiche',
        ),
    ]
