# Generated by Django 6.0.3 on 2026-09-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0070_remove_patient_fiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circb_app.ficheechantillon')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circb_app.patient')),
            ],
            options={
                'unique_together': {('fiche', 'patient')},
            },
        ),
    ]
