# Generated by Django 6.0.3 on 2026-09-28 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0072_remove_patient_fosa_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosa',
            name='parent',
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_districtuales', to='circb_app.structure'),
        ),
        migrations.RemoveField(
            model_name='fosa',
            name='hierachy',
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='fosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_fosa', to='circb_app.structure'),
        ),
        migrations.RemoveField(
            model_name='region',
            name='hierachy',
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_regionales', to='circb_app.structure'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_fosa', to='circb_app.structure'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Fosa',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
