# Generated by Django 6.0.3 on 2026-09-28 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0073_remove_fosa_parent_alter_ficheechantillon_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('hierachy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_structures', to='circb_app.structure_hierachy')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['nom'],
                'permissions': [('peut_voir_structures', 'Peut voir les structures'), ('peut_modifier_structures', 'Peut modifier les structures'), ('peut_supprimer_structures', 'Peut supprimer les structures'), ('peut_ajouter_structures', 'Peut ajouter de nouvelles structures')],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_districtuales', to='circb_app.district'),
        ),
        migrations.CreateModel(
            name='Fosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('hierachy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_structures', to='circb_app.structure_hierachy')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='circb_app.district')),
            ],
            options={
                'verbose_name': 'Fosa',
                'verbose_name_plural': 'Fosas',
                'ordering': ['nom'],
                'permissions': [('peut_voir_structures', 'Peut voir les structures'), ('peut_modifier_structures', 'Peut modifier les structures'), ('peut_supprimer_structures', 'Peut supprimer les structures'), ('peut_ajouter_structures', 'Peut ajouter de nouvelles structures')],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='fosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_fosa', to='circb_app.fosa'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('hierachy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_structures', to='circb_app.structure_hierachy')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
                'permissions': [('peut_voir_structures', 'Peut voir les structures'), ('peut_modifier_structures', 'Peut modifier les structures'), ('peut_supprimer_structures', 'Peut supprimer les structures'), ('peut_ajouter_structures', 'Peut ajouter de nouvelles structures')],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='circb_app.region'),
        ),
        migrations.AlterField(
            model_name='ficheechantillon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_regionales', to='circb_app.region'),
        ),
    ]
