# Generated by Django 6.0.3 on 2026-09-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0074_district_alter_ficheechantillon_district_fosa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='circb_app.patient'),
        ),
    ]
