# Generated by Django 6.0.3 on 2026-09-29 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0075_alter_fichepatient_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FosaTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fosa_nom', models.CharField(max_length=255, verbose_name='Nom de la FOSA au moment du transfert')),
                ('ancien_district', models.CharField(max_length=255, verbose_name='Ancien District')),
                ('nouveau_district', models.CharField(max_length=255, verbose_name='Nouveau District')),
                ('old_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ancien Code')),
                ('new_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nouveau Code')),
                ('fiches_mises_a_jour', models.IntegerField(default=0, verbose_name='Fiches échantillons modifiées')),
                ('patients_mis_a_jour', models.IntegerField(default=0, verbose_name='Patients mis à jour')),
                ('date_transfert', models.DateTimeField(auto_now_add=True, verbose_name='Date du transfert')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('fosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_logs', to='circb_app.fosa', verbose_name='Structure FOSA')),
            ],
            options={
                'verbose_name': 'Historique de transfert FOSA',
                'verbose_name_plural': 'Historiques de transferts FOSA',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
