# Generated by Django 6.0.3 on 2026-10-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0076_fosatransferlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSerologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(null=True)),
                ('ordre', models.PositiveIntegerField(null=True)),
                ('date_resultat', models.DateField(null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circb_app.patient')),
            ],
        ),
    ]
