# Generated by Django 6.0.3 on 2026-10-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0077_testserologique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='fiche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echantillons', to='circb_app.ficheechantillon'),
        ),
    ]
