# Generated by Django 6.0.3 on 2026-10-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0078_alter_echantillon_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testserologique',
            name='date_resultat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testserologique',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='testserologique',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_serologiques', to='circb_app.patient'),
        ),
        migrations.AlterField(
            model_name='testserologique',
            name='resultat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
