# Generated by Django 6.0.3 on 2026-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circb_app', '0079_alter_testserologique_date_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepatient',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
